//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS_API
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcademicTranscript
    {
        public int ClassSubjectId { get; set; }
        public int StudentId { get; set; }
        public Nullable<double> Score { get; set; }
    
        public virtual ClassSubject ClassSubject { get; set; }
        public virtual Student Student { get; set; }
    }
}
